name: The Cue
favicon: null
layout_spectrum: 0.13191
typography_spectrum: 0.5687
title: The Cue
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8a09a'
    - '#1e1611'
    - '#49372e'
    - '#6b5750'
    - '#c6c3c4'
  brandStrength: 0.6875
  lightness: 0.1541238478384912
  saturation: 0.25
  rhythmicContrast: 0.8847447521984577
purpose: []
